name: android_signature
description: A easy way to get android package signature on flutter app.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.github.sososdk.android_signature
        pluginClass: AndroidSignaturePlugin
